export type TMember = {
  id: number;
  username: string;
  name: string;
  state: string;
  locked: boolean;
  avatar_url: string;
  web_url: string;
  access_level: number;
  created_at: string;
  created_by: {
    id: number;
    username: string;
    name: string;
    state: string;
    locked: boolean;
    avatar_url: string;
    web_url: string;
  };
  expires_at: string;
};

export type TUser = {
  id: number,
  username: string,
  name: string,
  state: string,
  locked: boolean,
  avatar_url: string,
  web_url: string,
  created_at: string,
  bio: string,
  location: string,
  public_email: string,
  skype: string,
  linkedin: string,
  twitter: string,
  discord: string,
  website_url: string,
  organization: string,
  job_title: string,
  pronouns: string,
  bot: boolean,
  work_information: string,
  local_time: string,
  last_sign_in_at: string,
  confirmed_at: string,
  last_activity_on: string,
  email: string,
  theme_id: number,
  color_scheme_id: number,
  projects_limit: number,
  current_sign_in_at: string,
  identities: [],
  can_create_group: boolean,
  can_create_project: boolean,
  two_factor_enabled: boolean,
  external: boolean,
  private_profile: boolean,
  commit_email: string,
  is_admin: boolean,
  note: string,
  namespace_id: number,
  created_by: number,
  email_reset_offered_at: string
}

export type TUserInfo = {
  id: number,
  username: string,
  name: string,
  state: string,
  locked: boolean,
  avatar_url: string,
  web_url: string,
  created_at: string,
  bio: string,
  location: string,
  public_email: string,
  skype: string,
  linkedin: string,
  twitter: string,
  discord: string,
  website_url: string,
  organization: string,
  job_title: string,
  pronouns: string,
  bot: boolean,
  work_information: string,
  local_time: string,
  last_sign_in_at: string,
  confirmed_at: string,
  last_activity_on: string,
  email: string,
  theme_id: number,
  color_scheme_id: number,
  projects_limit: number,
  current_sign_in_at: string,
  identities: [],
  can_create_group: boolean,
  can_create_project: boolean,
  two_factor_enabled: boolean,
  external: boolean,
  private_profile: boolean,
  commit_email: string,
  is_admin: boolean,
  note: string,
  namespace_id: number,
  created_by: string,
  email_reset_offered_at: string,
  highest_role: number,
  current_sign_in_ip: string,
  last_sign_in_ip: string,
  sign_in_count: number
}